name: finance_tracker
description: "A new Flutter project to track finances including income and expenses."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # sqflite: ^2.0.0+4
  # sqflite_common_ffi: ^2.3.3  # Downgraded version
  sqflite_common_ffi: ^2.1.0
  sqflite: ^2.0.0+4
  path: ^1.8.3
  path_provider: ^2.0.11
  http: ^1.2.2  # Updated version
  provider: ^6.1.2 # Updated to a compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Add other dev dependencies like linting or code formatting tools if needed

flutter:
  uses-material-design: true

  # Uncomment and list any assets you want to include in your app here
  # assets:
  #   - assets/images/
  #   - assets/icons/
